export const elements = {
    // get ellements by class is LIVE unlike querySelectorAll
    playersNames: document.getElementsByClassName('player-name'),
    btnAddPlayer: document.querySelector('.btn-add-player'),
    btnsTeams:document.querySelector('.btns-teams'),
    btnsTimer:document.querySelector('.btns-timer'),
    btnsNumOfPhotos:document.querySelector('.btns-numOfPhotos'),
    btnsMinInputs:document.querySelector('.btns-min-inputs'),
    btnNextPage1: document.getElementById('btn-next1'),
    btnNextPage2:document.getElementById('btn-next-player'),
    btnNextPage3: document.getElementById('btn-next3'),
    playersList: document.querySelector('.players-list'),
    playersNamesDisplay: document.querySelector('.players-names-display'),
    teamsNamesDisplay: document.getElementById('teams-names-display'),
    textboxAddGuess:document.getElementById('textbox-add-guess'),
    btnAddGuess: document.getElementById('btn-add-guess'),
    playersGuessList:document.querySelector('.guess-list'),
    guessCountLabel: document.getElementById('id-counter'),
    guessCountFrame: document.querySelector('.label-counter'),
    settingsTab:document.getElementById('settings-tab'),
    gameTab:document.getElementById('game-tab'),
    restartTab:document.getElementById('restart-tab'),
    rulesTab:document.getElementById('rules-tab'),
    settingsPage:document.getElementById('settingsPage'),
    rulesPage:document.getElementById('rulesPage'),
    aboutPage:document.getElementById('aboutPage'),
    resultsPage:document.getElementById('resultsPage'),
    btnBack:document.getElementById('btn-back'),
    gameContainers:document.getElementsByClassName('game-container'),
    page1:document.getElementById('page1'),
    player0:document.getElementById('player-0'),
    textboxTeamsName:document.getElementById('textbox-teamsName'),
    labelMainName:document.getElementById('label-mainName'),
    teamsPlayers:document.getElementById('teams-players'),
    teamsColor:document.getElementById('teamsColor'),
    inGamePlayersDisplay:document.getElementById('inGame-playersDisplay'),
    inGameTimer:document.getElementById('timer-inGame'),
    inGamePlayerScore:document.getElementsByClassName('player-score'),
    inGameTeamScore:document.getElementsByClassName('team-score'),
    inGameNameToGuess:document.getElementById('inGame-nameToGuess'),
    inGamePhoto0: document.getElementById('guessPhoto0'),
    inGamePhoto1: document.getElementById('guessPhoto1'),
    inGamePhoto2: document.getElementById('guessPhoto2'),
    playerNameScore: document.getElementsByClassName('player-name-score'),
    btnStart: document.getElementById('btn-start'),
    btnPause: document.getElementById('btn-pause'),
    btnPauseText: document.getElementById('btn-pause-text'),
    btnSkip: document.getElementById('btn-skip'),
    btnGotit: document.getElementById('btn-gotit'),
    countdownLabel: document.getElementById('countdownLabel'),
    btnsBack: document.getElementsByClassName('btn-back')
};

export const elementStrings = {
    page1: 'page1',
    page2: 'page2',
    page3: 'page3',
    page4: 'page4',
    colorRed: 'rgb(255, 132, 132)',
    colorRedBG: 'rgba(255, 132, 132, 0.5)',
    colorGreen: '#28a745',
    colorGreenBG: '#28a74631',
    playerName: 'player-name',
    playerTextboxID: 'player-',
    btnDeletePlayerID: 'btn_delete_player-',
    newPlayerTextboxID: 'new_player-',
    btnTimerUP: 'btn-timer-up',
    btnTimerDown: 'btn-timer-down',
    btnTeamsUp: 'btn-teams-up',
    btnTeamsDown: 'btn-teams-down',
    btnNumOfPhotosUp: 'btn-numOfPhotos-down',
    btnNumOfPhotoDown: 'btn-numOfPhotos-down',
    btnDeleteGuess:'btn_delete_guess-'
};